"""restore expected travel time field

Revision ID: 10aa8e6cb440
Revises: 573ec9e2faf0
Create Date: 2026-07-22 05:01:54.814221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aa8e6cb440'
down_revision = '573ec9e2faf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_travel_time', sa.String(length=50), nullable=True))
        batch_op.drop_column('expected_travel_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_travel_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('expected_travel_time')

    # ### end Alembic commands ###
