"""rename expected travel time to expected travel date

Revision ID: 573ec9e2faf0
Revises: 767a729482b7
Create Date: 2026-07-22 04:54:43.242475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573ec9e2faf0'
down_revision = '767a729482b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_travel_date', sa.String(length=50), nullable=True))
        batch_op.drop_column('expected_travel_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_travel_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('expected_travel_date')

    # ### end Alembic commands ###
