"""expand booking information

Revision ID: 767a729482b7
Revises: 0653b6e68654
Create Date: 2026-07-22 04:21:24.481002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767a729482b7'
down_revision = '0653b6e68654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country_of_origin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('expected_travel_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('accommodation_preference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resident_adults', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resident_children', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('non_resident_adults', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('non_resident_children', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('number_of_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_people', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('destination',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('non_resident_children')
        batch_op.drop_column('non_resident_adults')
        batch_op.drop_column('resident_children')
        batch_op.drop_column('resident_adults')
        batch_op.drop_column('accommodation_preference')
        batch_op.drop_column('expected_travel_time')
        batch_op.drop_column('country_of_origin')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('passport_number')

    # ### end Alembic commands ###
